"""more robust ingredients/uom

Revision ID: 4a39cf2654f0
Revises: 042604bdaec0
Create Date: 2025-12-06 22:49:10.832023
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '4a39cf2654f0'
down_revision: Union[str, None] = '042604bdaec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_ingredients', sa.Column('category', sa.String(), nullable=True))
    op.add_column('stock_ingredients', sa.Column('synonyms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_ingredients', 'synonyms')
    op.drop_column('stock_ingredients', 'category')
    # ### end Alembic commands ###

