"""Beginning meal planning

Revision ID: 50fe459ab5d2
Revises: 8c76e8670c53
Create Date: 2025-12-16 22:41:55.398529
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '50fe459ab5d2'
down_revision: Union[str, None] = '8c76e8670c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_recipes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('yield_text', sa.String(), nullable=True),
    sa.Column('prep_time_minutes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('cook_time_minutes', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('ingredients', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False, server_default='[]'),
    sa.Column('notes', sa.JSON(), nullable=False, server_default='[]'),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_recipes_id'), 'stage_recipes', ['id'], unique=False)
    op.create_index(op.f('ix_stage_recipes_request_id'), 'stage_recipes', ['request_id'], unique=False)
    op.create_index(op.f('ix_stage_recipes_user_id'), 'stage_recipes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_recipes_user_id'), table_name='stage_recipes')
    op.drop_index(op.f('ix_stage_recipes_request_id'), table_name='stage_recipes')
    op.drop_index(op.f('ix_stage_recipes_id'), table_name='stage_recipes')
    op.drop_table('stage_recipes')
    # ### end Alembic commands ###

