"""Add recipe via url db changes

Revision ID: 8c76e8670c53
Revises: 9b030b4470dc
Create Date: 2025-12-12 23:54:21.871326
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '8c76e8670c53'
down_revision: Union[str, None] = '9b030b4470dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mailbox_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mailbox_messages_id'), 'mailbox_messages', ['id'], unique=False)
    op.create_index(op.f('ix_mailbox_messages_user_id'), 'mailbox_messages', ['user_id'], unique=False)
    op.create_table('recipe_ingestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('image_s3_keys', sa.JSON(), nullable=False),
    sa.Column('selected_tier', sa.Integer(), nullable=True),
    sa.Column('tier1_text', sa.Text(), nullable=True),
    sa.Column('tier2_text', sa.Text(), nullable=True),
    sa.Column('tier3_raw_response', sa.JSON(), nullable=True),
    sa.Column('pipeline_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tier_max', sa.Integer(), nullable=True),
    sa.Column('title_hint', sa.String(), nullable=True),
    sa.Column('recipe_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingestions_id'), 'recipe_ingestions', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_ingestions_user_id'), 'recipe_ingestions', ['user_id'], unique=False)
    op.add_column('recipe_parse_jobs', sa.Column('job_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_parse_jobs', 'job_data')
    op.drop_index(op.f('ix_recipe_ingestions_user_id'), table_name='recipe_ingestions')
    op.drop_index(op.f('ix_recipe_ingestions_id'), table_name='recipe_ingestions')
    op.drop_table('recipe_ingestions')
    op.drop_index(op.f('ix_mailbox_messages_user_id'), table_name='mailbox_messages')
    op.drop_index(op.f('ix_mailbox_messages_id'), table_name='mailbox_messages')
    op.drop_table('mailbox_messages')
    # ### end Alembic commands ###

