"""enhanced queue

Revision ID: 9b030b4470dc
Revises: 584ba5a42a56
Create Date: 2025-12-09 23:33:45.786483
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '9b030b4470dc'
down_revision: Union[str, None] = '584ba5a42a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add user_id with a temporary default to avoid failing on existing rows; then drop the default.
    op.add_column('recipe_parse_jobs', sa.Column('user_id', sa.String(), nullable=False, server_default=""))
    op.add_column('recipe_parse_jobs', sa.Column('committed_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_parse_jobs', sa.Column('abandoned_at', sa.DateTime(), nullable=True))
    op.add_column('recipe_parse_jobs', sa.Column('canceled_at', sa.DateTime(), nullable=True))
    op.create_index('ix_recipe_parse_jobs_completed_at', 'recipe_parse_jobs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_recipe_parse_jobs_user_id'), 'recipe_parse_jobs', ['user_id'], unique=False)
    op.create_index('ix_recipe_parse_jobs_user_status', 'recipe_parse_jobs', ['user_id', 'status'], unique=False)
    op.alter_column('recipe_parse_jobs', 'user_id', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipe_parse_jobs_user_status', table_name='recipe_parse_jobs')
    op.drop_index(op.f('ix_recipe_parse_jobs_user_id'), table_name='recipe_parse_jobs')
    op.drop_index('ix_recipe_parse_jobs_completed_at', table_name='recipe_parse_jobs')
    op.drop_column('recipe_parse_jobs', 'canceled_at')
    op.drop_column('recipe_parse_jobs', 'abandoned_at')
    op.drop_column('recipe_parse_jobs', 'committed_at')
    op.drop_column('recipe_parse_jobs', 'user_id')
    # ### end Alembic commands ###

